default:
  stackName: my-stack
  stage: production
  system_bucket:

  capabilities:
    - CAPABILITY_IAM

  lambdas:
    pyskel:
      handler: pyskel.handler.main
      source: package.zip
      timeout: 300
      memorySize: 1536
      runtime: python3.6
