version: 2
jobs:
  - test:
    docker:
      - image: circleci/python:3.6.5
        environment:
          - TOXENV=py36
          - UPLOAD_COVERAGE=1
    working_directory: ~/lambda-pyskel
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install tox codecov pre-commit --user
      - run:
          name: run tox
          command: ~/.local/bin/tox
      - run:
          name: run pre-commit
          command: |
            if [[ "$CIRCLE_JOB" == "python-3.6" ]]; then
               ~/.local/bin/pre-commit run --all-files
            fi
      - run:
          name: upload coverage report
          command: |
            if [[ "$UPLOAD_COVERAGE" == 1 ]]; then
               ~/.local/bin/coverage xml
               ~/.local/bin/codecov
            fi
          when: always

  - deploy:
      docker:
        - image: circleci/python:3.6.5
          environment:
            - TOXENV=release
      working_directory: ~/lambda-pyskel
      steps:
        - checkout
        - run:
            name: verify git tag vs. version
            command: |
              VERSION=$(python -c 'import lambda_pyskel; print(lambda_pyskel.__version__)')
              if [ $VERSION -eq $CIRCLE_TAG ]; then exit 0; else exit 3; fi
        - run:
            name: install dependencies
            command: pip install tox codecov pre-commit --user
        - run:
            name: init .pypirc
            command: |
              echo -e "[pypi]" >> ~/.pypirc
              echo -e "username = $PYPI_USER" >> ~/.pypirc
              echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
        - run:
            name: run tox
            command: ~/.local/bin/tox

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
