service: pyskel

provider:
  name: aws
  runtime: python3.6
  stage: production

package:
  artifact: package.zip

functions:
  pyskel:
    handler: pyskel.handler.main
    memorySize: 1536
    timeout: 300
